### ISSUE TITLE
Refreshing data on disconnected device causes app to crash

### ISSUE THREAD

**Issue by steven7gn** [particle-iot/particle-tinker-app-ios#9] opened 2016-09-03 14:55 UTC
1.    Registered user, existing device running Tinker.
2.    Disconnect device from network (e.g. press setup button to get RGB LED blinking blue
3.    In app, go into device inspector, bring up the More Actions dialog.
4.    Click on refresh data

App will crash.   This doesn't happen on other device actions.

(Not doing active hunting for bugs-- just happened to stumble on this because my device had disconnected itself somehow and I was enjoying exploring the new features that have been added :)

**Comment by idokleinman** [comment] 2016-09-06 21:43
Managed to reproduce. Thanks for reporting! Working on fixing this now

**Comment by idokleinman** [comment] 2016-09-06 21:43
Managed to reproduce. Thanks for reporting! Working on fixing this now

**Comment by idokleinman** [comment] 2016-09-06 23:10
Managed to reproduce. Thanks for reporting! Working on fixing this now

**Comment by idokleinman** [comment] 2016-09-06 23:10
Managed to reproduce. Thanks for reporting! Working on fixing this now

**Comment by idokleinman** [comment] 2016-09-08 03:10
Finally found root cause of this bug - this has revealed a bug in the iOS Cloud SDK which was fixed on 0.5.1 as well as in the app v2.0 build 7. Thank you!

**Closed as completed by idokleinman** 2016-09-08 03:10 UTC

**Comment by steven7gn** [comment] 2016-09-11 23:11
Thanks, Ido-- glad you were able to fix.  I updated to Spark_SDK 0.5.1 and this time refreshing data on a     disconnected device worked just fine.  It was a bit odd that the last heard time went back to several days earlier-- perhaps an issue in the cloud service somewhere, not sure.   After re-connecting the device and refreshing the data, it correctly reported the data.
