### ISSUE TITLE
Can't reflash tinker app from either simulator or mobile device

### ISSUE THREAD

**Issue by steven7gn** [particle-iot/particle-tinker-app-ios#6] opened 2016-07-14 20:34 UTC
I did a rest install of version latest commit 61ecbd1 (May 09), installed dependencies via cocoa pod, built, and ran.  Have generally tested most features including running the tinker app and toggling pins successfully.  However, I can't seem to get the flash/reflash to operate.  The SettingsTableViewController.swift call to self.device.FlashFiles! doesn't seem to return and the debug window doesn't return a successful completion.  If I'm in this state and go to my iPhone and run the production version of Tinker and do a reflash-- surprisingly the debug window on the simulator will show a successful completion message upon conclusion of the iPhone initiated refresh.  I'm brand new to iOS swift development and so perhaps there is something that is understood that needs to be done with the main file bundle that I don't know to do? 

-Steve

**Comment by idokleinman** [comment] 2016-07-14 23:44
Thanks for reporting, this is a known bug, root cause in the Cloud SDK, it will be fixed in the upcoming 0.5.0 SDK release.

**Closed as completed** 2016-09-15 18:25 UTC
